FROM minio/mc:latest

COPY data_playlist.csv /data_playlist.csv
COPY data_playlist_batch.csv /data_playlist_batch.csv
COPY svm_model.pkl /svm_model.pkl
COPY danceability.pkl /danceability.pkl
COPY energy.pkl /energy.pkl
COPY speechiness.pkl /speechiness.pkl
